sudo: required
services:
  - docker

before_install:
  - docker build -t basantmo/docker-react -f Dockerfile.dev .

sceipts:
  - docker run basantmo/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-735419623860"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: "AWS_ACCESS_KEY"
    secret_access_key: "AWS_SECRET_KEY"
